import subprocess
import os
import signal
import sys
import time
import threading
from pathlib import Path

# Configuration
BACKEND_DIR = Path("myeongshim_rag")
FRONTEND_DIR = Path(".")
BACKEND_PORT = 8000
FRONTEND_PORT = 3000

def check_env():
    """Checks environment variables and dependencies."""
    print("🔍 [System Check] Verifying Environment...")

    # 1. Check Python Venv
    if not (BACKEND_DIR / "venv").exists():
        print(f"⚠️  Warning: Python venv not found in {BACKEND_DIR}/venv. Ensure dependencies are installed.")
        # Attempt to see if we are already in a venv or just system python (agent environment)
    else:
        print("✅ Python venv found.")

    # 2. Check Node Modules
    if not (FRONTEND_DIR / "node_modules").exists():
        print("⚠️  Warning: node_modules not found. Run 'npm install' first.")
    else:
        print("✅ node_modules found.")

    # 3. Check RAG URL in Env (Heuristic read of .env.local)
    env_local = FRONTEND_DIR / ".env.local"
    if env_local.exists():
        try:
            content = env_local.read_text(encoding="utf-8")
            if "RAG_SERVER_URL" not in content:
                print("⚠️  Warning: RAG_SERVER_URL is missing in .env.local.")
                print("   Action: Add 'RAG_SERVER_URL=http://localhost:8000' to .env.local")
            else:
                print("✅ RAG_SERVER_URL found in .env.local.")
        except Exception as e:
            print(f"⚠️  Could not read .env.local: {e}")
    else:
        print("ℹ️  .env.local not found. Creating default configuration...")
        try:
            with open(".env.local", "a", encoding="utf-8") as f:
                f.write("\n# Auto-generated by main.py\nRAG_SERVER_URL=http://127.0.0.1:8000\n")
            print("✅ Created .env.local with RAG_SERVER_URL.")
        except Exception as e:
            print(f"❌ Failed to create .env.local: {e}")

    # 4. Check RAG DB Status
    check_rag_db()

def check_rag_db():
    """Checks if RAG vector DB exists. If not, runs ingestion."""
    db_path = BACKEND_DIR / "db"
    
    # Check if DB directory exists and is not empty
    if not db_path.exists() or not any(db_path.iterdir()):
        print("⚠️  RAG Database not found or empty.")
        print("⚙️  Running initial ingestion (this may take a minute)...")
        
        # Determine python executable
        python_exec = "python"
        venv_python = BACKEND_DIR / "venv" / "Scripts" / "python.exe"
        if venv_python.exists():
            python_exec = str(venv_python)
            
        try:
            # Run ingestion script
            subprocess.run(
                [python_exec, "-m", "src.ingest"], 
                cwd=BACKEND_DIR, 
                check=True
            )
            print("✅ Ingestion complete.")
        except subprocess.CalledProcessError as e:
            print(f"❌ Ingestion failed: {e}")
            print("   Please check 'myeongshim_rag/data' and requirements.")
    else:
        print("✅ RAG Database found.")

def stream_output(process, prefix, color_code):
    """Reads output from a subprocess and prints it with a prefix."""
    for line in iter(process.stdout.readline, ""):
        if not line: break
        # ANSI colors: \033[94m (Blue), \033[92m (Green), \033[0m (Reset)
        print(f"\033[{color_code}m[{prefix}]\033[0m {line.strip()}")
    process.stdout.close()

def run_processes():
    processes = []
    
    # 1. Start Backend (FastAPI)
    print("🚀 Starting Backend (Myeongshim RAG)...")
    
    # Determine python executable (venv or system)
    python_exec = "python"
    venv_python = BACKEND_DIR / "venv" / "Scripts" / "python.exe"
    if venv_python.exists():
        python_exec = str(venv_python)
    
    # Command: uvicorn api:app --reload --port 8000
    backend_cmd = [python_exec, "-m", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", str(BACKEND_PORT), "--reload"]
    
    try:
        backend_proc = subprocess.Popen(
            backend_cmd,
            cwd=BACKEND_DIR,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT, # Merge stderr to stdout
            text=True,
            bufsize=1  # Line buffered
        )
        processes.append(backend_proc)
        
        # Start logging thread
        t_be = threading.Thread(target=stream_output, args=(backend_proc, "BACKEND", "92")) # Green
        t_be.daemon = True
        t_be.start()
        
    except Exception as e:
        print(f"❌ Failed to start Backend: {e}")
        return

    # 2. Start Frontend (Next.js)
    print("🚀 Starting Frontend (Next.js)...")
    npm_cmd = ["npm.cmd", "run", "dev"] if os.name == 'nt' else ["npm", "run", "dev"]
    
    try:
        frontend_proc = subprocess.Popen(
            npm_cmd,
            cwd=FRONTEND_DIR,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1
        )
        processes.append(frontend_proc)
        
        t_fe = threading.Thread(target=stream_output, args=(frontend_proc, "FRONTEND", "94")) # Blue
        t_fe.daemon = True
        t_fe.start()
        
    except Exception as e:
        print(f"❌ Failed to start Frontend: {e}")
        # Kill backend if frontend fails
        backend_proc.terminate()
        return

    print(f"\n✨ System Integrated. Access at http://localhost:{FRONTEND_PORT}")
    print("Example: Type '/test_rag' in the chat to verify connection.\n")

    try:
        # Keep main thread alive
        while True:
            time.sleep(1)
            # Check if processes are alive
            if backend_proc.poll() is not None:
                print("❌ Backend stopped unexpectedly.")
                break
            if frontend_proc.poll() is not None:
                print("❌ Frontend stopped unexpectedly.")
                break
    except KeyboardInterrupt:
        print("\n🛑 Shutting down services...")
        for p in processes:
            p.terminate()
    finally:
        print("👋 Goodbye.")

if __name__ == "__main__":
    print("""
=============================================
   ☯️  Myeongshim Coaching - Unified Loader
=============================================
""")
    check_env()
    run_processes()
