-- 1. Enable Vector Extension
create extension if not exists vector;

-- 2. Create Knowledge Store Table
create table if not exists knowledge_store (
  id bigint generated by default as identity primary key,
  content text, 
  embedding vector(768), -- Gemini 2.5 Flash / embedding-004 Dimension
  metadata jsonb,
  created_at timestamptz default now()
);

-- 3. Enable RLS
alter table knowledge_store enable row level security;

-- 4. Create Policy (Allow All for MVP/Dev)
-- Note: In production, limit write access to service_role only.
drop policy if exists "Allow all" on knowledge_store;
create policy "Allow all" on knowledge_store for all using (true);
