-- [Fix] Users Table Columns
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS current_stage integer DEFAULT 1;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS subscription_tier text DEFAULT 'free';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email text;

-- [Fix] Chat Logs Table
CREATE TABLE IF NOT EXISTS public.chat_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.users(id),
    role text NOT NULL, -- 'user' or 'assistant'
    message text NOT NULL,
    stage integer DEFAULT 1,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Permisssions
ALTER TABLE public.chat_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.chat_logs
    FOR SELECT USING (true);

CREATE POLICY "Enable insert access for all users" ON public.chat_logs
    FOR INSERT WITH CHECK (true);

-- Grant access to anon (for demo)
GRANT ALL ON public.chat_logs TO anon;
GRANT ALL ON public.chat_logs TO authenticated;
GRANT ALL ON public.users TO anon;
GRANT ALL ON public.users TO authenticated;
