-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. USERS Table
create table public.users (
  id uuid primary key default uuid_generate_v4(),
  email text,
  saju_data jsonb, -- {"year": "甲寅", "day": "丙午", ...}
  subscription_tier text default 'free', -- free, basic, premium
  current_stage integer default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for users
alter table public.users enable row level security;
create policy "Users can view their own data" on public.users for select using (auth.uid() = id);
create policy "Users can update their own data" on public.users for update using (auth.uid() = id);


-- 2. COACHING_SESSIONS Table (Context Memory)
create table public.coaching_sessions (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references public.users(id) on delete cascade not null,
  stage_level integer not null,
  summary text, -- AI summary of this stage for next prompts
  action_plan jsonb, -- {"mission": "Diary", "status": "done"}
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for coaching_sessions
alter table public.coaching_sessions enable row level security;
create policy "Users can view their own sessions" on public.coaching_sessions for select using (auth.uid() = user_id);
create policy "Users can insert their own sessions" on public.coaching_sessions for insert with check (auth.uid() = user_id);


-- 3. CHAT_LOGS Table (History)
create table public.chat_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  role text not null, -- 'user' or 'assistant'
  content text not null,
  stage_context integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for chat_logs
alter table public.chat_logs enable row level security;
create policy "Users can view their own chats" on public.chat_logs for select using (auth.uid() = user_id);
create policy "Users can insert their own chats" on public.chat_logs for insert with check (auth.uid() = user_id);
